pragma Singleton
import QtQuick 2.0

QtObject {

    readonly property string arrow: "\uE000"
    readonly property string circle : "\uE001"
    readonly property string cloud : "\uE002"
    readonly property string raindrop : "\uE003"
    readonly property string fire : "\uE004"
    readonly property string house : "\uE005"
    readonly property string filledcircle : "\uE006"
    readonly property string raining : "\uE007"
    readonly property string reset : "\uE045"
    readonly property string timer : "\uE008"
    readonly property string clock : "\uE009"
    readonly property string eye : "\uE00A"
    readonly property string logo : "\uE044"
    readonly property string gauge : "\uE00B"
    readonly property string sun : "\uE00C"
    readonly property string cloudsun : "\uE00D"
    readonly property string lightoff : "\uE00E"
    readonly property string lighton : "\uE00F"
    readonly property string settings : "\uE010"
    readonly property string heart : "\uE011"
    readonly property string book : "\uE012"
    readonly property string child : "\uE013"
    readonly property string alarmclock : "\uE014"
    readonly property string presence : "\uE015"
    readonly property string wifi : "\uE016"
    readonly property string mic : "\uE017"
    readonly property string bluetooth : "\uE018"
    readonly property string web : "\uE019"
    readonly property string speechbubble : "\uE01A"
    readonly property string ampere : "\uE01B"
    readonly property string motion : "\uE01C"
    readonly property string electric : "\uE01D"
    readonly property string close : "\uE01E"
    readonly property string leaf : "\uE01F"
    readonly property string socket : "\uE020"
    readonly property string temp : "\uE021"
    readonly property string tesla : "\uE022"
    readonly property string raspi : "\uE023"
    readonly property string privacy : "\uE024"
    readonly property string circle2 : "\uE025"
    readonly property string bell : "\uE026"
    readonly property string nobell : "\uE027"
    readonly property string moon : "\uE028"
    readonly property string freeze : "\uE029"
    readonly property string whatsapp : "\uE02A"
    readonly property string touch : "\uE02B"
    readonly property string settings2 : "\uE02C"
    readonly property string storm : "\uE02D"
    readonly property string fan : "\uE03D"
    readonly property string shutter : "\uE035"
    readonly property string doublearrow : "\uE034"
    readonly property string usb : "\uE033"
    readonly property string magnet : "\uE032"
    readonly property string phone : "\uE031"
    readonly property string test1 : "\uE03F"
    readonly property string test2 : "\uE036"
    readonly property string compass : "\uE030"
    readonly property string trash : "\uE02E"
    readonly property string cam : "\uE02F"
    readonly property string wind : "\uE040"
    readonly property string sunset : "\uE041"
    readonly property string sunrise : "\uE042"
    readonly property string schedule : "\uE043"
    readonly property string speaker : "\uE046"

    readonly property string graph : "\uE049"


}
